name: "Evaluation"
on:
  pull_request:
  push:
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@main
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable      
    - run: nix build --dry-run --file release.nix
    - run: nix flake check -L

# potential improvements:
#   - populate a Cachix cache with realtime kernels (speed/disk space)
#   - figure out the purpose of "nix build --dry-run --file release.nix"
